//
//	You may customize this code as you like
//	Report bugs to: https://silentorbit.com/protobuf-csharpgen/
//
//	Generated by ProtocolBuffer
//	- a pure c# code generation implementation of protocol buffers
//

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using ProtocolBuffers;

namespace ExampleNamespace
{

	public partial class Person : IPerson
	{
		public string Name { get; set; }
		public int Id { get; set; }
		public string Email { get; set; }
		public List<Person.IPhoneNumber> Phone { get; set; }
	
		public partial class PhoneNumber : IPhoneNumber
		{
			public string Number { get; set; }
			public Person.PhoneType Type { get; set; }
		
		}
	
	}

	public partial class MyMessageV1 : IMyMessageV1
	{
		public int FieldA { get; set; }
	
	}

	public partial class MyMessageV2 : IMyMessageV2
	{
		public int FieldA { get; set; }
		public double FieldB { get; set; }
		public float FieldC { get; set; }
		public int FieldD { get; set; }
		public long FieldE { get; set; }
		public uint FieldF { get; set; }
		public ulong FieldG { get; set; }
		public int FieldH { get; set; }
		public long FieldI { get; set; }
		public uint FieldJ { get; set; }
		public ulong FieldK { get; set; }
		public int FieldL { get; set; }
		public long FieldM { get; set; }
		public bool FieldN { get; set; }
		public string FieldO { get; set; }
		public byte[] FieldP { get; set; }
		public MyMessageV2.MyEnum FieldQ { get; set; }
		public MyMessageV2.MyEnum FieldR { get; set; }
		public string Dummy { get; set; }
		public List<uint> FieldS { get; set; }
		public List<uint> FieldT { get; set; }
		public ITheirMessage FieldU { get; set; }
		public List<ITheirMessage> FieldV { get; set; }
	
	}

	public partial class TheirMessage : ITheirMessage
	{
		public int FieldA { get; set; }
	
	}

}
